[build]
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/survey"
  to = "/survey.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

